### PR TITLE
Implement .to_a for irange and erange

### LINKED ISSUE #45: Support irange.to_a
I'm just putting this here as a memo to myself. I will create a PR a bit later 👍 

We could quite easily support following notation:
```ruby
(0..4).to_a
```

In javascript:
```js
[...Array(5)].map((_,i) => i);  // [0, 1, 2, 3, 4]
// Or
[...Array(5).keys()] // [0, 1, 2, 3, 4]
```

I know that full irange support is quite hard but I know that we already do support it in few contexts.

Source: https://stackoverflow.com/questions/3746725/create-a-javascript-array-containing-1-n

### PR DESCRIPTION
**Pull request by onnimonni**
This is just a initial implementation. Review and tips to make this cleaner highly wanted 👍

Fixes #45 

It's easier to view with whitespaces ignored: https://github.com/rubys/ruby2js/pull/47/files?utf8=%E2%9C%93&diff=unified&w=1

### CODE REVIEW

**Comment by onnimonni** [comment]
I didn't implement the step function yet but it should be quite easy to add after wise.

Thanks for your help @rubys!

**Comment by onnimonni** [comment]
This works now but it's still quite problematic for code like this:
```ruby
v=10
puts (0...v).to_a
```
Outputs:
```js
let k = 5;
let v = 10;
console.log(Array.from({length: (v-k)}, (v, k) => k+k))
```

**Comment by rubys** [comment]
> Can we check if certain variables are used in the scope?

Yes:

```ruby
    @vars.include? :v
```

Alternately, JavaScript allows variables to contains a `$` character anywhere in the name.  Ruby global variables start with a `$` character, so ruby2js will not generate any code which contains a `$` anyplace but the first character.

**Comment by onnimonni** [comment]
For me this looks good to go, but ofc I'm waiting for your final inputs.

**Comment by rubys** [comment]
Two things I would like to see fixed first, then something to think about.

  * There needs to be some mention of this in the README.  It doesn't have to show the complete set of possibilities, but some indication that range.to_a is supported and an example mapping.  And preferably some indication that specifying a higher level of es will improve the output.  All in all, two lines should suffice.
  * fat arrow functions (`=>`) don't exist in es5.  This would need to be a `function` with a `return` statement.

Now the thing to think about.  You might be able reduce the code a bit and handle eslevel more correctly by replacing the `put` statements with `parse` statements.  Something like the following should work independent of the eslevel.

```
parse s(:block, s(:send, nil, :proc, s(:args, s(:arg, :_), s(:arg, :idx),
  s(:return, s(:send, s(:lvar, :idx), :+, s(:lvar, :b)))
```

This third comment is not a blocker.  Proceed with what you feel most comfortable with.

**Pull request merged**
