### PR TITLE
Tagged template literals

### PR DESCRIPTION
**Pull request by jaredcwhite**
This is a first pass at a filter which allows a list of tags for prefixing template literal strings. It will convert this:

```ruby
output = html "some text here"
```

to this:

```js
let output = html`some text here`
```

It works with any length of string as well as heredocs. I also provided a customization option for the filter…by default it looks for `html` and `css` but you can change it to look for any tags you want using the `template_literal_tags` option.

I also made sure it doesn't process anything if there's a target for the send, aka `self.html` or `some_obj.html` or whatever. Should work around most edge cases.

Probably should be a separate PR, but I also fixed a few bugs with the camelCase filter. When using an underscore prefix, before it would turn `_method_name` into `MethodName` rather than `_methodName`. I also made it support numbers (`foo_bar_123` becomes `fooBar123`) and method calls using suffixes like `=`, `?`, and `!`.

Let me know what you think!

### CODE REVIEW

**Comment by jaredcwhite** [comment]
Looks like tests prior to 2.3 are failing…is supporting those versions still a requirement? (Ruby 2.5 is now the oldest officially supported version to the best of my knowledge.)

**Comment by jaredcwhite** [comment]
One issue I found: escaping backticks in a JS template literal requires doing `` \` ``, but can't seem to get that to output correctly out of the Ruby code. It either swallows the backslash or I get two backslashes. This seems to be an existing issue, prior to this PR.

**Comment by jaredcwhite** [comment]
OK, that should be fixed now.

**Comment by rubys** [comment]
Feel free to drop versions of Ruby prior to 2.3.

**Comment by rubys** [comment]
Consider updating the README?

**Comment by jaredcwhite** [comment]
Sure, yeah I didn't want to get into docs too much until the approach seemed good to you. Will work on that shortly.

**Comment by jaredcwhite** [comment]
All right, I added docs to the readme and tests are passing now. Looks good to merge?

**Review by rubys — APPROVED** [review]
LGTM.  

* `ruby2js.gemspec` needs to have `required_ruby_version` updated before a new gem is pushed.
* consider having `filter/tagged_templates.rb` require ruby2js/es2015 - this isn't mandatory, but any JS implementation that supports tagged templates should also support `let`, `class`, arrow functions and other goodies added in es2015.

**Comment by rubys** [comment]
Now moot, but worth noting that without es2015

`html "foo#{bar}"` produces `html"foo" + bar`

**Comment by jaredcwhite** [comment]
> Now moot, but worth noting that without es2015
> 
> `html "foo#{bar}"` produces `html"foo" + bar`

Yep, good call to add that minimum es2015 requirement for the filter.

**Pull request merged**
