### PR TITLE
adds simple sprocket support

### PR DESCRIPTION
**Pull request by rubydesign**
Not perfect (and untested), but does the job for me.

### CODE REVIEW

**Comment by rubydesign** [comment]
There is something amiss here. The first commit works in dev, but the second in production.
But neither in the other.

I have a more pressing problem (issue coming up :-) ), if i can resolve that i will dig into this one.

**Comment by rubydesign** [comment]
Ok, now it works for me in dev and production.
One just has to do a configure block.

**Comment by rubys** [comment]
> One just has to do a configure block.

Perhaps document this someplace?

**Comment by rubydesign** [comment]
Sprocket activates when the rails file is loaded.
I puts some info into the rails.rb.
At the moment i don't see another place for more docs, but i'd be happy to write if you suggest where.

**Pull request merged**
